### ISSUE TITLE
Upgrade ?

### ISSUE THREAD

**Issue by dalede01** [redgeoff/openvpn-server-vagrant#11]
Hello All,
    I have been running openvpn-server-vagrant on aws for a couple of years now.. on Ubuntu 16.04

I am considering upgrading this server to Ubuntu 20...

If I do this will it impact the rendition of openvpn-server-vagrant?
Is there an update to the actual openvpn server itself and how would I apply it?

Thank you for your time and consideration.

Dale

**Comment by redgeoff** [comment]
Fixed by https://github.com/redgeoff/openvpn-server-vagrant/pull/13
