### ISSUE TITLE
Upgrading openvpn server from 16.04 to latest ubuntu release ?

### ISSUE THREAD

**Issue by amolvishwakarma** [redgeoff/openvpn-server-vagrant#12]
Hi @redgeoff ,

Currently I am running openvpn vagrant server on ubuntu 16.04 but after upgrading to ubuntu latest release For ex: 20.04 . I am not able to connect to openvpn server with any of my openvpn user profiles.

**Comment by redgeoff** [comment]
Fixed by https://github.com/redgeoff/openvpn-server-vagrant/pull/13
