### ISSUE TITLE
The openvpn.sh file doesn't work with Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by gregglowrimore** [redgeoff/openvpn-server-vagrant#8]
The make-cadir creates a folder with a default vars file. In that vars file, there is a whichopensslcnf call that doesn't work with the openssl-*.cnf files laid out by the make-cadir. It needs another elif block to check for openssl-1.1.0.cnf to match the openssl version in 18.04 LTS.

**Comment by redgeoff** [comment]
Thanks @gregglowrimore. Would you be willing to submit a PR?

**Comment by saidmasoud** [comment]
Hi @gregglowrimore 

Could you tell me where the `openssl-1.1.0.cnf` file is located? I could not find it on my 18.04 machine, I only found an `openssl-1.0.0.cnf` file. I have a temporary/hacky fix in place until this repo is updated to support 18.04.

**Comment by ronnythedev** [comment]
Is there a way to get the hacky fix? Currently AWS does not allow to create instances with an older version of Ubutu I think

**Comment by ronnythedev** [comment]
Never mind, there is a way to use Ubuntu 16.04.

**Comment by saidmasoud** [comment]
sorry @ron-camaron !!! I actually ended up using the below repo instead since the `add-client.sh` script still didn't work after getting the install to work. Unfortunately, it's a prompt-based script and the maintainer isn waiting for a PR to add flags for automation, but it worked for me.

https://github.com/angristan/openvpn-install

**Comment by vaughnd** [comment]
Had to fix this manually. Trouble is that make-cadir from easy-rsa 2.2.2 that comes with Ubuntu 18 doesn't deal with openssl-1.1.0.cnf yet. I had to re-run openvpn.sh and let it create the openvpn-ca directory, then ctrl-c out, cp /etc/ssl/openssl.cnf openvpn-ca/openssl-1.1.0.cnf, then run openvpn.sh again and it worked.

**Comment by cvernooy23** [comment]
@vaughnd I tried the workaround you mentioned, but to no avail. I ended up using the project mentioned by @saidmasoud which worked fine.

**Comment by redgeoff** [comment]
Fixed by https://github.com/redgeoff/openvpn-server-vagrant/pull/13
